window.onload = function () {
	createInsult()
}

// Source for negative adjectives: https://www.englishclub.com/vocabulary/adjectives-personality-negative.htm
let adjectives = [
	"aggressive",
	"aloof",
	"arrogant",
	"belligerent",
	"big-headed",
	"bitchy",
	"boastful",
	"boring",
	"bossy",
	"callous",
	"cantankerous",
	"careless",
	"clinging",
	"compulsive",
	"cowardly",
	"cruel",
	"cunning",
	"cynical",
	"deceitful",
	"detached",
	"dishonest",
	"domineering",
	"finicky",
	"foolish",
	"foolhardy",
	"fussy",
	"greedy",
	"grumpy",
	"gullible",
	"impatient",
	"impolite",
	"impulsive",
	"inconsiderate",
	"inconsistent",
	"indecisive",
	"indiscreet",
	"inflexible",
	"interfering",
	"intolerant",
	"irresponsible",
	"jealous",
	"lazy",
	"Machiavellian",
	"mean",
	"moody",
	"narrow-minded",
	"nasty",
	"obsessive",
	"obstinate",
	"overcritical",
	"overemotional",
	"parsimonious",
	"patronizing",
	"perverse",
	"pessimistic",
	"pompous",
	"possessive",
	"pusillanimous",
	"resentful",
	"rude",
	"sarcastic",
	"selfish",
	"self-centred",
	"self-indulgent",
	"silly",
	"sneaky",
	"stingy",
	"stubborn",
	"stupid",
	"superficial",
	"tactless",
	"timid",
	"touchy",
	"thoughtless",
	"unkind",
	"unreliable",
	"untidy",
	"untrustworthy",
	"vain",
	"vengeful",
	"vulgar",
	"weak-willed"
]

// Thanks to borlaym from github for the animals.json! https://gist.github.com/borlaym/585e2e09dd6abd9b0d0a
let animal = [
	"Aardvark",
	"Alligator",
	"Alpaca",
	"Ant",
	"Anteater",
	"Antelope",
	"Ape",
	"Armadillo",
	"Donkey",
	"Baboon",
	"Badger",
	"Bat",
	"Bear",
	"Beaver",
	"Bison",
	"Boar",
	"Buffalo",
	"Camel",
	"Caribou",
	"Cat",
	"Caterpillar",
	"Cattle",
	"Chicken",
	"Chimpanzee",
	"Clam",
	"Cobra",
	"Cockroach",
	"Cod",
	"Coyote",
	"Crab",
	"Crocodile",
	"Deer",
	"Dog",
	"Dolphin",
	"Duck",
	"Eagle",
	"Eel",
	"Elephant",
	"Elk",
	"Emu",
	"Ferret",
	"Fish",
	"Fox",
	"Frog",
	"Gerbil",
	"Giraffe",
	"Gnat",
	"Goat",
	"Goldfish",
	"Goose",
	"Gorilla",
	"Grasshopper",
	"Gull",
	"Hippopotamus",
	"Hornet",
	"Horse",
	"Hyena",
	"Ibex",
	"Jackal",
	"Jellyfish",
	"Kangaroo",
	"Lemur",
	"Llama",
	"Lobster",
	"Locust",
	"Manatee",
	"Mandrill",
	"Mantis",
	"Meerkat",
	"Mole",
	"Mongoose",
	"Monkey",
	"Moose",
	"Mosquito",
	"Mouse",
	"Mule",
	"Narwhal",
	"Newt",
	"Octopus",
	"Opossum",
	"Ostrich",
	"Owl",
	"Oyster",
	"Parrot",
	"Pelican",
	"Penguin",
	"Pig",
	"Pigeon",
	"Pony",
	"Porcupine",
	"Rabbit",
	"Raccoon",
	"Ram",
	"Rat",
	"Reindeer",
	"Rhinoceros",
	"Salamander",
	"Salmon",
	"Sardine",
	"Scorpion",
	"Seal",
	"Sheep",
	"Shrew",
	"Skunk",
	"Snail",
	"Snake",
	"Spider",
	"Squid",
	"Squirrel",
	"Stingray",
	"Stinkbug",
	"Tapir",
	"Termite",
	"Toad",
	"Trout",
	"Turkey",
	"Turtle",
	"Vulture",
	"Wallaby",
	"Walrus",
	"Wasp",
	"Weasel",
	"Whale",
	"Wombat",
	"Worm",
	"Yak",
	"Zebra"
]

// Pulled from http://www.slate.com/blogs/lexicon_valley/2013/09/11/top_swear_words_most_popular_curse_words_on_facebook.html
let cuss = [
	"shit",
	"fuck",
	"bitch",
	"piece of crap",
	"dick",
	"cock",
	"pussy",
	"asshole",
	"fag",
	"bastard",
	"slut",
	"douche"
]


/* Returns a random number between 0 - arrayLength */
function randomArray(array) {
	let arrayLength = array.length
	return ( Math.floor(Math.random() * arrayLength) )
}

/* Prints generated insult to DOM */
function createInsult () {
	let firstRandomAdjective = adjectives[randomArray(adjectives)]
	let randomAnimal = (animal[randomArray(animal)]).toLowerCase()
	let secondRandomAdjective = adjectives[randomArray(adjectives)]
	let randomCuss = cuss[randomArray(cuss)]

	let insult = "You're such a " + firstRandomAdjective + " " + randomAnimal +
		", you " + secondRandomAdjective + " " + randomCuss + "!"

	document.getElementById('insultTarget').innerHTML = insult
}
